// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owvnundowwqsqddmctmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93dm51bmRvd3dxc3FkZG1jdG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NzM2NDUsImV4cCI6MjA2MTQ0OTY0NX0.GN7NzIBuAOZ7s6Q_-5E2CPfwndEFfImkOPj_7BL0hlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);